import { Employee } from '../models/employee.model';

export const Employees: Employee[] = [
  {
    id: 1,
    firstname: 'Rajani',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-01.jpg',
    category: 'IT',
  },
  {
    id: 2,
    firstname: 'Ravi',
    lastname: 'nadimpalli',
    birthdate: '1996-11-91',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-01.jpg',
    category: 'Non IT',
  },
  {
    id: 3,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1996-01-92',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-01.jpg',
    category: 'Non IT',
  },
  {
    id: 4,
    firstname: 'Nimisha',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-02.jpg',
    category: 'IT',
  },
  {
    id: 5,
    firstname: 'sai',
    lastname: 'nadimpalli',
    birthdate: '1996-08-98',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 11,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 6,
    firstname: 'shravya',
    lastname: 'M',
    birthdate: '1996-07-22',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 11,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 7,
    firstname: 'Divya',
    lastname: 'V',
    birthdate: '1996-01-96',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 11,
    profile: 'Profile-03.jpg',
    category: 'Non IT',
  },
  {
    id: 8,
    firstname: 'Banu',
    lastname: 'V',
    birthdate: '1996-01-99',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 11,
    profile: 'Profile-03.jpg',
    category: 'Non IT',
  },
  {
    id: 9,
    firstname: 'santosh',
    lastname: 'N',
    birthdate: '1996-01-96',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 11,
    profile: 'Profile-03.jpg',
    category: 'Non IT',
  },
  {
    id: 10,
    firstname: 'Vamsi',
    lastname: 'V',
    birthdate: '1996-01-96',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 11,
    profile: 'Profile-03.jpg',
    category: 'Non IT',
  },
];
